-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Diagnostico"
(
    id_diagnostico serial NOT NULL,
    id_tipo_robot serial NOT NULL,
    id_tipo_problemas serial NOT NULL,
    id_tipo_reparacion serial NOT NULL,
    CONSTRAINT "Diagnostico_pkey" PRIMARY KEY (id_diagnostico)
);

CREATE TABLE IF NOT EXISTS public.tipo_reparaciones
(
    id_tipo_reparacion serial NOT NULL,
    "descripción_solucion" "char" NOT NULL,
    tiempo_garantia "char" NOT NULL,
    CONSTRAINT tipo_reparaciones_pkey PRIMARY KEY (id_tipo_reparacion)
);

COMMENT ON TABLE public.tipo_reparaciones
    IS 'Tipo de Reparación  (soluciones técnicas)

';

CREATE TABLE IF NOT EXISTS public.tipo_robots
(
    id_tipo_robot serial NOT NULL,
    descripcion_robot "char" NOT NULL,
    CONSTRAINT tipo_robots_pkey PRIMARY KEY (id_tipo_robot)
);

CREATE TABLE IF NOT EXISTS public.tipos_problemas
(
    id_tipo_problemas serial NOT NULL,
    descripcion "char" NOT NULL,
    CONSTRAINT tipos_problemas_pkey PRIMARY KEY (id_tipo_problemas)
);

ALTER TABLE IF EXISTS public."Diagnostico"
    ADD CONSTRAINT diagnostico_tipo_reparaciones_fk FOREIGN KEY (id_tipo_reparacion)
    REFERENCES public.tipo_reparaciones (id_tipo_reparacion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Diagnostico"
    ADD CONSTRAINT diagnostico_tipo_robots_fk FOREIGN KEY (id_tipo_robot)
    REFERENCES public.tipo_robots (id_tipo_robot) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Diagnostico"
    ADD CONSTRAINT diagnostico_tipos_problemas_fk FOREIGN KEY (id_tipo_problemas)
    REFERENCES public.tipos_problemas (id_tipo_problemas) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;